---
dist: focal
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-software-properties
      - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: virtualbox
    - MOLECULE_DISTRO: coglinev3/ansible
    - PATH: /home/travis/.local/bin:${PATH}
  matrix:
    - MOLECULE_DISTRO_VERSION: centos-6
    - MOLECULE_DISTRO_VERSION: centos-7
    - MOLECULE_DISTRO_VERSION: centos-8
    - MOLECULE_DISTRO_VERSION: fedora-31
    - MOLECULE_DISTRO_VERSION: fedora-32
    - MOLECULE_DISTRO_VERSION: debian-10
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: ubuntu-18.04
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: ubuntu-20.04
      MOLECULE_DISTRO_CMD: /bin/systemd

install:
  # Install test dependencies.
  - pip3 install -U jinja2 requests ansible molecule yamllint ansible-lint docker

before_script:
  - lsmod
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  # Configure Ansible
  - cp .travis/ansible.cfg ~/.ansible.cfg
  - mkdir -p ~/.ansible && cp .travis/hosts ~/.ansible
  # Show Ansible version
  - ansible --version
  # Create roles directory
  - ln -s $(pwd)/.. ~/.ansible/roles
  # Install VirtualBox on the host system
  - ansible-playbook .travis/virtualbox.yml
  # Load the VirtualBox driver on the host system
  - sudo /sbin/vboxconfig


script:
  # Run tests.
  - molecule lint
  - molecule create
  - molecule converge
  # Load the VirtualBox driver on the host system again
  - sudo /sbin/vboxconfig
  - molecule verify
  - molecule destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
