---
dist: focal
addons:
  apt:
    packages:
      - python3-pip
      - python3-testresources
      - libssl-dev

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: virtualbox
    - MOLECULE_DISTRO: coglinev3/ansible
    - PATH: /home/travis/.local/bin:${PATH}
  matrix:
    - MOLECULE_DISTRO_VERSION: centos-6
      MOLECULE_DISTRO_CMD: /sbin/init
    - MOLECULE_DISTRO_VERSION: centos-7
    - MOLECULE_DISTRO_VERSION: centos-8
    - MOLECULE_DISTRO_VERSION: fedora-31
    - MOLECULE_DISTRO_VERSION: fedora-32
    - MOLECULE_DISTRO_VERSION: debian-8
      MOLECULE_DISTRO_CMD: /sbin/init
    - MOLECULE_DISTRO_VERSION: debian-9
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: debian-10
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: ubuntu-16.04
      MOLECULE_DISTRO_CMD: /sbin/init
    - MOLECULE_DISTRO_VERSION: ubuntu-18.04
      MOLECULE_DISTRO_CMD: /bin/systemd
    - MOLECULE_DISTRO_VERSION: ubuntu-20.04
      MOLECULE_DISTRO_CMD: /bin/systemd

install:
  # Upgrade setuptools
  - python3 -m pip install --upgrade --user setuptools
  # Install Ansible Molecule with docker driver and lint tools
  - python3 -m pip install --upgrade --user "molecule[ansible,docker,lint]"

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  # Configure Ansible
  - cp .travis/ansible.cfg ~/.ansible.cfg
  - mkdir -p ~/.ansible && cp .travis/hosts ~/.ansible
  # Show Ansible and Molecule versions
  - ansible --version
  - molecule --version
  # Create roles directory
  - mkdir -p ~/.ansible/roles
  # Install latest stable version of this role via Ansible Galaxy
  - ansible-galaxy install -r requirements.yml -p ~/.ansible/roles
  # Install VirtualBox on the host system
  - ansible-playbook .travis/virtualbox.yml
  # Load the VirtualBox driver on the host system
  - sudo /sbin/vboxconfig

script:
  # Run tests.
  - molecule lint
  - molecule create
  - molecule converge
  # Load the VirtualBox driver on the host system again
  - sudo /sbin/vboxconfig
  - molecule verify
  - molecule destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
