---
# file: roles/virtualbox/tasks/main.yml

- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: vars

- name: Setup/install tasks.
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"
- name: Configure VBox users.
  ansible.builtin.include_tasks: manage_vbox_users.yml
