---
# file: roles/virtualbox/tasks/manage_vbox_users.yml

- name: Adding existing users to group vboxusers
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: "yes"
  when: vbox_installed.skipped is not defined
  loop: "{{ vbox_users|flatten(levels=1) }}"
  loop_control:
    label: "{{ item }}"
