---
# file: roles/virtualbox/tasks/setup-RedHat.yml

- name: "RedHat: Install dependencies"
  ansible.builtin.yum:
    name: "{{ vbox_dependencies }}"
    update_cache: "yes"
    state: present

- name: "RedHat: Add Oracle's signing key"
  ansible.builtin.rpm_key:
    key: "{{ oracle_public_key }}"
    state: "{{ oracle_public_key_state }}"

- name: "RedHat: Configure Oracle VirtualBox repository"
  ansible.builtin.template:
    src: yum-repo.j2
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644
  when: not ansible_distribution == "Fedora"

- name: "Fedora: Configure Oracle VirtualBox repository"
  ansible.builtin.template:
    src: yum-repo-fedora.j2
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Fedora"

- name: "RedHat: Install VirtualBox"
  ansible.builtin.yum:
    name: "{{ vbox_package }}"
    enablerepo: virtualbox
    update_cache: "yes"
    state: "{{ vbox_package_state | default('latest') }}"
  register: vbox_installed
