---
# file: roles/virtualbox/tasks/setup-RedHat.yml


- name: Setup a kernel_devel variable
  set_fact:
    kernel_devel: "kernel-devel-{{ ansible_kernel }}"

- name: Setup a kernel_headers variable
  set_fact:
    kernel_headers: "kernel-headers-{{ ansible_kernel }}"

- name: Initialize an empty list essential_packages
  set_fact:
    vbox_essential_packages: []

- name: Add EPEL Repository to  essential_packages
  set_fact:
    vbox_essential_packages: "{{ vbox_essential_packages + [ 'epel-release' ] }}"

- name: Append kernel-devel for current kernel to essential_packages
  set_fact:
    vbox_essential_packages: "{{ vbox_essential_packages + [ kernel_devel ] }}"
  when: ansible_virtualization_type != "docker"

- name: Append kernel-headers for current kernel to essential_packages
  set_fact:
    vbox_essential_packages: "{{ vbox_essential_packages + [ kernel_headers ] }}"
  when: ansible_virtualization_type != "docker"


- debug:
    var: vbox_essential_packages

# Ensure kernel-headers and kernel-devel have the same version like the kernel
- name: "RedHat: Install EPEL and kernel packages"
  yum:
    name: "{{ vbox_essential_packages }}"
    update_cache: "yes"
    state: present

- name: "RedHat: Install dependencies"
  yum:
    name: "{{ vbox_dependencies }}"
    update_cache: "yes"
    enablerepo: epel
    state: present

- name: "RedHat: Add Oracle's signing key"
  rpm_key:
    key: "{{ oracle_public_key }}"
    state: "{{ oracle_public_key_state }}"

- name: "RedHat: Configure Oracle VirtualBox repository"
  template:
    src: yum-repo.j2
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644
  register: vbox_repo

- name: "RedHat: Install VirtualBox"
  yum:
    name: "{{ vbox_package }}"
    enablerepo: virtualbox
    update_cache: "yes"
    state: "{{ vbox_package_state | default('latest') }}"
  register: vbox_installed
  when: vbox_repo.dest is defined
