---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: "Log in as user ansible and execute VBoxManage --version"
      become: true
      become_user: ansible
      shell: VBoxManage --version
      changed_when: false
      args:
        warn: false # set warn=false to prevent warning
      register: vbox_version
    - name: Check VirtualBox version
      assert:
        that:
          - "'6.1' in vbox_version.stdout"
        fail_msg: "VirtualBox not installed properly"
        success_msg: "VirtualBox {{ vbox_version.stdout }} installed correctly"
